baseURL: "https://statsf18.classes.andrewheiss.com/"
languageCode: en-us
title: Data Science for Public Management
theme: "ath-tufte-hugo_18-19"
googleAnalytics: ""
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - \.yaml$
  - _files$
  - _cache$
  - \.csl$
permalinks:
  post: "/:year/:month/:day/:slug/"
buildFuture: true
menu:
  main:
    - name: Syllabus
      url: /syllabus/
      weight: 1
    - name: Assignments
      url: /assignments/
      weight: 3
    - name: Schedule
      url: /schedule/
      weight: 2
    - name: Reference
      url: /reference/
      weight: 4
    - name: RStudio.cloud
      url: "https://rstudio.cloud"
      weight: 5
    - name: DataCamp
      url: "https://www.datacamp.com/enterprise/byu-mpa-630-fall-2018/"
      weight: 6
    - name: Class chat
      url: "https://gitter.im/byustatsf18/"
      weight: 7
# Disable taxonomies
taxonomies:
  tag: ""
  group: ""
  category: ""
params:
  author: Andrew Heiss
  thumbnail: /images/stats_meta.png
  instructor: 
    name: Dr. Andrew Heiss
    email: andrew_heiss@byu.edu
    url: "https://www.andrewheiss.com"
    twitter: andrewheiss
    github: andrewheiss
    office: 639 TNRB
  course:
    number: MPA 630
    semester: Fall 2018
    days: "Th"
    time: "7:35–9:45 PM"
    location: "417 SLC"
    twitter: andrewheiss
    dates: "September 6–December 13, 2018"
    github: "andrewheiss/statsf18.classes.andrewheiss.com"
    copyrightYear: "2018"
    contactDetails: >-
      Office hours: TBD. [Sign up for other times here.](https://calendly.com/andrewheiss/meeting/)<br><br>E-mail is the best way to get in contact with me—I will respond to all course-related e-mails within 24 hours (*really*).
  university: 
    name: Brigham Young University
    url: "https://www.byu.edu"
  school:
    name: Romney Institute of Public Service and Ethics
    url: "https://marriottschool.byu.edu/mpa/"
  description: "Use modern statistical and data scientific tools to work with data and improve public management, administration, and policy"
  primaryColor: "#D46600"
  secondaryColor: "#F6E03F"
  credits: >-
    Hex icon by Andrew Heiss. Color scheme adapted from [October Roads](http://www.colourlovers.com/palette/582235/October_Roads).<br>Course content adapted in part from [MATH 116 (Albert Kim)](https://rudeboybert.github.io/MATH116/), [STA 199 (Mine Çetinkaya-Rundel)](https://www2.stat.duke.edu/courses/Spring18/Sta199/), [SOC 301 (Chester Ismay)](https://ismayc.github.io/soc301_s2017/), and [CONJ 620 (Alison Presmanes Hill)](https://apreshill.github.io/ohsu-basic-stats/).
  logo:
    url: /images/stats_hires.png
    alt: Data Science for Public Management
  meta:
    twitterSite: "@andrewheiss"
    twitterCreator: "@andrewheiss"
    fbAuthor: "https://www.facebook.com/andrewheiss"
